#!/usr/bin/env python3
"""Validate every runs/*/triage.json and rebuild practice_changing.md, the accumulating index of
practice-changing items across all runs.

The index is generated, never edited by hand: it is a view of runs/, so it can always be rebuilt.
Read-only with respect to state/ and runs/.
Usage: python scripts/build_index.py [--check]   (--check validates without writing)
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "practice_changing.md"
RELEVANCE = ("practice-changing", "high", "medium", "low")
KINDS = ("trial", "regulatory", "guideline")
KIND_LABEL = {"trial": "Trial", "regulatory": "Regulatory", "guideline": "Guideline"}


def load_runs():
    """[(run_id, triage, {first_key: item})] for every run that has a triage.json."""
    runs = []
    for d in sorted((ROOT / "runs").glob("*/")):
        t = d / "triage.json"
        if not t.exists():
            continue
        n = d / "new_items.json"
        items = json.loads(n.read_text(encoding="utf-8")) if n.exists() else []
        runs.append((d.name, json.loads(t.read_text(encoding="utf-8")),
                     {it["keys"][0]: it for it in items if it.get("keys")}))
    return runs


def validate(runs):
    errors = []
    for run_id, triage, items in runs:
        for key, t in triage.items():
            where = f"runs/{run_id}/triage.json: {key}"
            rel = t.get("relevance")
            if rel not in RELEVANCE:
                errors.append(f"{where}: relevance {rel!r} is not one of {', '.join(RELEVANCE)}")
            if rel != "practice-changing":
                continue
            pc = t.get("practice_change") or {}
            if pc.get("kind") not in KINDS:
                errors.append(f"{where}: practice_change.kind must be one of {', '.join(KINDS)}")
            if not str(pc.get("basis", "")).strip():
                errors.append(f"{where}: practice_change.basis is required")
            if key not in items:
                errors.append(f"{where}: not in runs/{run_id}/new_items.json")
    return errors


def entry(run_id, key, t, it):
    pc = t["practice_change"]
    date = f"{run_id[0:4]}-{run_id[4:6]}-{run_id[6:8]}"
    cite = ", ".join(x for x in (it.get("authors"), it.get("journal"), str(it.get("year") or "")) if x)
    if it.get("source") == "feed":
        cite = (cite + ", " if cite else "") + "preprint"
    lines = [
        f"### {it.get('title', key).rstrip('.')}",
        f"- **{KIND_LABEL[pc['kind']]}** · first seen {date} · "
        f"[digest {run_id}](digests/{run_id}.md) · searches: {', '.join(it.get('searches', []))}",
        f"- **Basis:** {pc['basis'].strip()}",
    ]
    if t.get("reason"):
        lines.append(f"- **Why:** {t['reason'].strip()}")
    lines.append(f"- {cite + ' · ' if cite else ''}{it.get('url', '')}"
                 + (f" (doi {it['doi']})" if it.get("doi") and it.get("source") == "pubmed" else ""))
    return "\n".join(lines)


def render(runs):
    found = [(run_id, key, t, items[key]) for run_id, triage, items in runs
             for key, t in triage.items() if t.get("relevance") == "practice-changing"]
    found.sort(key=lambda r: r[0], reverse=True)
    out = [
        "# Practice-changing items",
        "",
        "Generated by `scripts/build_index.py` from every `runs/*/triage.json`. Do not edit by hand.",
        "The bar is the `practice_changing` rubric in `searches.yaml`; each search adds its own line.",
        "",
        f"{len(found)} item(s) across {len(runs)} triaged run(s), newest first.",
    ]
    if found:
        out += ["", "\n\n".join(entry(*r) for r in found)]
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only, do not write the index")
    args = ap.parse_args()
    runs = load_runs()
    errors = validate(runs)
    for e in errors:
        print(f"ERROR {e}", file=sys.stderr)
    if errors:
        sys.exit(1)
    if not args.check:
        OUT.write_text(render(runs), encoding="utf-8")
    n = sum(1 for _, tr, _ in runs for t in tr.values() if t.get("relevance") == "practice-changing")
    print(f"{'checked' if args.check else 'wrote ' + OUT.name}: {n} practice-changing item(s) in {len(runs)} run(s)")


if __name__ == "__main__":
    main()
